# Generated by Django 4.2.4 on 2023-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.TextField(help_text='Модель авто', max_length=60)),
                ('creator', models.TextField(help_text='Производитель', max_length=100)),
                ('first_year', models.CharField(help_text='Начало выпуска', max_length=4)),
                ('last_year', models.CharField(help_text='Окончание', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_email', models.EmailField(max_length=254)),
                ('car', models.TextField(help_text='Модель авто', max_length=60)),
                ('create_date', models.DateField()),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Производитель', max_length=60)),
                ('country', models.TextField(help_text='Страна', max_length=60)),
            ],
        ),
    ]
