# Generated by Django 4.2.4 on 2023-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.CharField(help_text='Окончание выпуска', max_length=4),
        ),
    ]
