# Generated by Django 4.2.4 on 2023-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_last_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.CharField(help_text='Окончание выпуска(если производится до сих пор - нв', max_length=4),
        ),
    ]
