# Generated by Django 4.2.4 on 2023-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_last_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'Creator', 'verbose_name_plural': 'Creators'},
        ),
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.CharField(help_text='Окончание выпуска(если производится до сих пор - нв)', max_length=4),
        ),
    ]
