# Generated by Django 4.2.4 on 2023-08-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_car_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': ('Машина',), 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': ('Коммент',), 'verbose_name_plural': 'Комменты'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': ('Страна',), 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': ('Производитель',), 'verbose_name_plural': 'Производители'},
        ),
    ]
